### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by petrparolek**
- Travis CI -> GitHub Actions
- fixed code reported by PHPStan

### CODE REVIEW

**Comment by uestla** [comment]
Thank you @petrparolek for these changes.
I have a rebased & refactored version of this project locally and I'm planning of force-pushing it.

After that I'll review your changes.
Until then - is there any reason for replacing composer scripts with Makefile? Cannot composer scripts be run in Github Actions as well? Just asking...

**Comment by uestla** [comment]
Thank you @petrparolek for these changes.
I have a rebased & refactored version of this project locally and I'm planning to force-push it later today.

After that I'll review your changes.
Until then - is there any reason for replacing composer scripts with Makefile? Cannot composer scripts be run in Github Actions as well? Just asking...

**Comment by petrparolek** [comment]
Composer scripts vs. makefile - I unified over all contributte packages.

**Comment by f3l1x** [comment]
Yep, just make it same as in other repos here. If you don't have make installed on your OS, just let us know. :-)

**Comment by uestla** [comment]
Sorry, the force-push somehow closed the pull request, didn't mean to do that.
I'll try to pull it locally and merge it if I can.

I was just asking about the Makefile - personally I'm more used to composer scripts (have bash aliases for them etc.), so I was curious if there are any problems with them at Github Actions. On the other hand, I'd vote for keeping composer scripts and call them in Makefile (may seem kinda weird, but that could make both sides happy) :-)

**Comment by f3l1x** [comment]
Composer scripts + Makefile sounds good to me.

**Comment by uestla** [comment]
I just cherry-picked the "Travis CI -> GitHub Actions" commit and made a few tweaks:

- used newer shivammathur/setup-php@v2 (v1 is deprecated)
- using composer scripts in Makefile
- explicitly calling `make install` instead of default target
- moved schema:create & fixtures from Makefile to GA definition (`schema` is supposed to just check the annotations)
- used newer syntax for code-checker (multiple folders)
- added other checkers added in the rebase/force-push (phplint, coding-standards, tests renamed to tester)

**Comment by uestla** [comment]
I just cherry-picked the "Travis CI -> GitHub Actions" commit and made a few tweaks:

- used newer shivammathur/setup-php@v2 (v1 is deprecated)
- using composer scripts in Makefile
- explicitly calling `make install` instead of default target
- moved `schema:create` & fixtures from Makefile to GA definition (`schema` is supposed to just check the annotations)
- used newer syntax for `code-checker` (multiple folders)
- added other checkers added in the rebase/force-push (phplint, coding-standards, tests renamed to tester)

**Comment by uestla** [comment]
I just cherry-picked the "Travis CI -> GitHub Actions" commit and made a few tweaks:

- used newer shivammathur/setup-php@v2 (v1 is deprecated)
- using composer scripts in Makefile
- explicitly calling `make install` instead of default target
- moved `schema:create` & fixtures from Makefile to GA definition (`schema` is supposed to just check the annotations)
- used newer syntax for `code-checker` (multiple folders)
- added other checkers added in the rebase/force-push (phplint, coding-standards, tests renamed to tester)

**Comment by uestla** [comment]
I just cherry-picked the "Travis CI -> GitHub Actions" commit and made a few tweaks:

- used newer shivammathur/setup-php@v2 (v1 is deprecated)
- using composer scripts in Makefile
- explicitly calling `make install` instead of default target
- moved `schema:create` & fixtures from Makefile to GA definition (`schema` is supposed to just check the annotations)
- used newer syntax for `code-checker` (multiple folders)
- added other checkers added in the rebase/force-push (phplint, coding-standards, tests renamed to tester)

**Comment by uestla** [comment]
I just cherry-picked the "Travis CI -> GitHub Actions" commit and made a few tweaks:

- used newer shivammathur/setup-php@v2 (v1 is deprecated)
- using composer scripts in Makefile
- explicitly calling `make install` instead of default target
- moved `schema:create` & fixtures from Makefile to GA definition (`schema` is supposed to just check the annotations)
- used newer syntax for `code-checker` (multiple folders)
- added other checkers added in the rebase/force-push (phplint, coding-standards, tests renamed to tester)

**Pull request closed without merging**
